### ISSUE TITLE
Update is required because of a change in the layout-base library 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/avsdf-base#1]
Please update [this line](https://github.com/iVis-at-Bilkent/avsdf-base/blob/783a031c9f14b3dfbccd4f5d217321bf14dffd86/src/AVSDFNode.js#L78) because getNeighborsList function returns a Javascript Set anymore.

**Comment by alihanokka** [comment]
Fixed references to layout-base that returns an outdated HashSet structure.
